name: Simple website

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Get Latest Tag
      run: echo "VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKERPWD }}" | docker login -u "tomasburkon" --password-stdin
        docker image build -t tomasburkon/test-github-actions:${{ env.VERSION }} .
        docker push tomasburkon/test-github-actions:${{ env.VERSION }}
